# Generated by Django 2.1.5 on 2019-02-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo_nodes_v6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(choices=[('Fixed Income', 'Fixed Income'), ('Foreign Exchange', 'Foreign Exchange'), ('Derivatives', 'Derivatives'), ('Equities', 'Equities')], max_length=266),
        ),
        migrations.AlterField(
            model_name='recordset',
            name='name',
            field=models.CharField(blank=True, choices=[('Settlements', 'Settlements'), ('Orders', 'Orders'), ('Trades', 'Trades'), ('Customer Details', 'Customer Details')], max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('EMEA', 'EMEA'), ('AMER', 'AMER'), ('APAC', 'APAC')], max_length=266),
        ),
    ]
