# Generated by Django 2.1.5 on 2019-02-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo_nodes_v6', '0002_auto_20190223_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(choices=[('Equities', 'Equities'), ('Foreign Exchange', 'Foreign Exchange'), ('Fixed Income', 'Fixed Income'), ('Derivatives', 'Derivatives')], max_length=266),
        ),
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(choices=[('Region', 'Region'), ('System', 'System'), ('RecordSet', 'RecordSet')], max_length=266),
        ),
        migrations.AlterField(
            model_name='recordset',
            name='name',
            field=models.CharField(blank=True, choices=[('Settlements', 'Settlements'), ('Customer Details', 'Customer Details'), ('Orders', 'Orders'), ('Trades', 'Trades')], max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('APAC', 'APAC'), ('EMEA', 'EMEA'), ('AMER', 'AMER')], max_length=266),
        ),
        migrations.RemoveField(
            model_name='system',
            name='businesses',
        ),
        migrations.AddField(
            model_name='system',
            name='businesses',
            field=models.ManyToManyField(related_name='_system_businesses_+', to='neo_nodes_v6.System'),
        ),
        migrations.RemoveField(
            model_name='system',
            name='regions',
        ),
        migrations.AddField(
            model_name='system',
            name='regions',
            field=models.ManyToManyField(related_name='_system_regions_+', to='neo_nodes_v6.System'),
        ),
    ]
