# Generated by Django 2.1.5 on 2019-02-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo_nodes_v6', '0003_auto_20190224_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(choices=[('Derivatives', 'Derivatives'), ('Fixed Income', 'Fixed Income'), ('Foreign Exchange', 'Foreign Exchange'), ('Equities', 'Equities')], max_length=266),
        ),
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(choices=[('Region', 'Region'), ('RecordSet', 'RecordSet'), ('System', 'System')], max_length=266),
        ),
        migrations.AlterField(
            model_name='recordset',
            name='format',
            field=models.CharField(blank=True, choices=[('Database record', 'Database record'), ('Archive record', 'Archive record')], max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='recordset',
            name='name',
            field=models.CharField(blank=True, choices=[('Orders', 'Orders'), ('Customer Details', 'Customer Details'), ('Trades', 'Trades'), ('Settlements', 'Settlements')], max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('EMEA', 'EMEA'), ('APAC', 'APAC'), ('AMER', 'AMER')], max_length=266),
        ),
        migrations.RemoveField(
            model_name='system',
            name='businesses',
        ),
        migrations.AddField(
            model_name='system',
            name='businesses',
            field=models.CharField(blank=True, max_length=266),
        ),
        migrations.RemoveField(
            model_name='system',
            name='regions',
        ),
        migrations.AddField(
            model_name='system',
            name='regions',
            field=models.CharField(blank=True, max_length=266),
        ),
    ]
