# Generated by Django 2.1.5 on 2019-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo_nodes_v6', '0005_auto_20190224_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordset',
            name='label',
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(choices=[('Derivatives', 'Derivatives'), ('Equities', 'Equities'), ('Foreign Exchange', 'Foreign Exchange'), ('Fixed Income', 'Fixed Income')], max_length=266),
        ),
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(choices=[('Region', 'Region'), ('System', 'System'), ('RecordSet', 'RecordSet')], max_length=266),
        ),
        migrations.AlterField(
            model_name='recordset',
            name='name',
            field=models.CharField(blank=True, choices=[('Orders', 'Orders'), ('Trades', 'Trades'), ('Customer Details', 'Customer Details'), ('Settlements', 'Settlements')], max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('AMER', 'AMER'), ('APAC', 'APAC'), ('EMEA', 'EMEA')], max_length=266),
        ),
    ]
