# Generated by Django 2.1.5 on 2019-02-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('RecordSet', 'RecordSet'), ('Region', 'Region'), ('System', 'System')], max_length=266)),
            ],
        ),
        migrations.CreateModel(
            name='RecordSet',
            fields=[
                ('name', models.CharField(blank=True, choices=[('Orders', 'Orders'), ('Customer Details', 'Customer Details'), ('Trades', 'Trades'), ('Settlements', 'Settlements')], max_length=266, null=True)),
                ('id', models.CharField(max_length=266, primary_key=True, serialize=False)),
                ('dataContactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('dataContactName', models.CharField(blank=True, max_length=266, null=True)),
                ('EpochFrom', models.CharField(blank=True, max_length=266, null=True)),
                ('format', models.CharField(blank=True, choices=[('Archive record', 'Archive record'), ('Database record', 'Database record')], max_length=266, null=True)),
                ('availableFrom', models.CharField(blank=True, max_length=266, null=True)),
                ('availableTo', models.CharField(blank=True, max_length=266, null=True)),
                ('businessContactPhone', models.CharField(max_length=266)),
                ('EpochTo', models.CharField(blank=True, max_length=266, null=True)),
                ('businessContactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('dataContactPhone', models.CharField(blank=True, max_length=266, null=True)),
                ('businessContactName', models.CharField(blank=True, max_length=266)),
                ('extractionSLA', models.CharField(blank=True, max_length=266)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(choices=[('APAC', 'APAC'), ('EMEA', 'EMEA'), ('AMER', 'AMER')], max_length=266)),
                ('id', models.CharField(max_length=266, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('name', models.CharField(max_length=266)),
                ('ownerPhoneNumber', models.CharField(blank=True, max_length=266)),
                ('regions', models.CharField(max_length=266)),
                ('ownerName', models.CharField(blank=True, max_length=266)),
                ('id', models.CharField(max_length=266, primary_key=True, serialize=False)),
                ('businesses', models.CharField(max_length=266)),
                ('ownerEmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
