# Generated by Django 2.1.5 on 2019-02-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo_nodes_v5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(choices=[('Region', 'Region'), ('RecordSet', 'RecordSet'), ('System', 'System')], max_length=266),
        ),
        migrations.AlterField(
            model_name='recordset',
            name='format',
            field=models.CharField(blank=True, choices=[('Database record', 'Database record'), ('Archive record', 'Archive record')], max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='recordset',
            name='name',
            field=models.CharField(blank=True, choices=[('Orders', 'Orders'), ('Settlements', 'Settlements'), ('Trades', 'Trades'), ('Customer Details', 'Customer Details')], max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('AMER', 'AMER'), ('APAC', 'APAC'), ('EMEA', 'EMEA')], max_length=266),
        ),
    ]
